apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    # Replace with the Apache/Loki host IP or DNS reachable from Grafana machine.
    url: http://<APACHE_LOKI_HOST>:3100
